#include "pch.h"

#define TRUSTCIRCUIT_ENCLAVE_FAMILY_ID \
    { \
        0x54, 0x72, 0x75, 0x73, 0x74, 0x43, 0x69, 0x72, \
        0x63, 0x75, 0x69, 0x74, 0x56, 0x42, 0x53, 0x01, \
    }

#define TRUSTCIRCUIT_ENCLAVE_IMAGE_ID \
    { \
        0x54, 0x43, 0x56, 0x42, 0x53, 0x50, 0x48, 0x41, \
        0x53, 0x45, 0x31, 0x00, 0x00, 0x00, 0x00, 0x01, \
    }

#define TRUSTCIRCUIT_ENCLAVE_IMAGE_VERSION 0xA065F400
#define TRUSTCIRCUIT_ENCLAVE_SVN 1
#define TRUSTCIRCUIT_ENCLAVE_ADDRESS_SPACE_SIZE 0x20000000
#define TRUSTCIRCUIT_ENCLAVE_MAX_THREADS 16

constexpr int enclavePolicyEnableDebuggingForDebugBuildsOnly{
#ifdef _DEBUG
    IMAGE_ENCLAVE_POLICY_DEBUGGABLE
#endif
};

extern "C" const IMAGE_ENCLAVE_CONFIG __enclave_config = {
    sizeof(IMAGE_ENCLAVE_CONFIG),
    IMAGE_ENCLAVE_MINIMUM_CONFIG_SIZE,
    enclavePolicyEnableDebuggingForDebugBuildsOnly,
    0,
    0,
    0,
    TRUSTCIRCUIT_ENCLAVE_FAMILY_ID,
    TRUSTCIRCUIT_ENCLAVE_IMAGE_ID,
    TRUSTCIRCUIT_ENCLAVE_IMAGE_VERSION,
    TRUSTCIRCUIT_ENCLAVE_SVN,
    TRUSTCIRCUIT_ENCLAVE_ADDRESS_SPACE_SIZE,
    TRUSTCIRCUIT_ENCLAVE_MAX_THREADS,
    IMAGE_ENCLAVE_FLAG_PRIMARY_IMAGE};

BOOL WINAPI DllMain(HINSTANCE, DWORD, LPVOID)
{
    return TRUE;
}
